UMCS-326: Added a Json-Validation before real Json-Deserialization ha…
unzerdev/java-sdk pull request #64
Opened 2022-02-07 16:58 UTC by DerAusHeidelberg

…ppens and added tests for it. Positive Tests for `fromJson` are not possible because of recursive references inside most of the Payment-relevant Classes (e.g. Unzer reference).

2022-02-08 10:04 UTC, sixer1182 requested changes
Please add tests for json == null

2022-02-08 10:29 UTC, sixer1182 reviewed
LGTM

2022-02-08 10:29 UTC, sixer1182 approved these changes
LGTM

2022-02-08 10:58 UTC, Ryouzanpaku approved these changes
LGTM,
I would add an entry in the changelog for it, though.

2022-02-08 12:35 UTC, sixer1182 approved these changes
LGTM

2022-02-10 14:41 UTC, Ryouzanpaku submitted a review, later dismissed
LGTM.

2022-02-11 14:43 UTC, Ryouzanpaku approved these changes

2022-02-14 14:23 UTC, merged